class Food {
  Food({
    required this.price,
    required this.name,
    required this.path,
    required this.description,
  });
  final double price;
  final String name;
  final String path;
  final String description;
}

List<Food> foodslist = [
  Food(
    name: 'Frango Grelhado',
    price: 12.50,
    description: 'Frango grelhado temperado com ervas frescas.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Frango à Parmegiana',
    price: 15.25,
    description: 'Peito de frango empanado com molho',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Frango com Batatas',
    price: 18.50,
    description: 'Frango assado com batatas temperadas.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Frango à Milanesa',
    price: 10.85,
    description: 'Filé de frango empanado e frito.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Frango Xadrez',
    price: 22.75,
    description: 'Frango salteado com legumes e molho especial.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Salada de Frango',
    price: 16.00,
    description: 'Salada fresca com peito de frango grelhado.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Coxinha de Frango',
    price: 8.50,
    description: 'Coxinha de frango assada com massa crocante.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Frango ao Curry',
    price: 14.50,
    description: 'Frango cozido com molho de curry e arroz.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Frango Teriyaki',
    price: 19.00,
    description: 'Frango grelhado com molho teriyaki e legumes.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Sopa de Frango',
    price: 3.50,
    description: 'Sopa quente com pedaços de frango e legumes.',
    path: 'lib/images/FRANGO10.png',
  ),
  Food(
    name: 'Sopa de Legumes',
    price: 3.50,
    description: 'Sopa quente com uma mistura de legumes frescos.',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Caldo de Frango',
    price: 3.50,
    description: 'Caldo nutritivo com pedaços de frango e ervas.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Sopa de Milho',
    price: 3.50,
    description: 'Sopa cremosa de milho com temperos suaves.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Creme de Abóbora',
    price: 3.50,
    description: 'Creme de abóbora com um toque de gengibre.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Sopa de Tomate',
    price: 3.50,
    description: 'Sopa de tomate com manjericão e alho.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Canja de Galinha',
    price: 3.50,
    description: 'Canja de galinha com arroz e cenoura.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Caldo Verde',
    price: 3.50,
    description: 'Caldo verde com couve e pedaços de linguiça.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Sopa de Batata',
    price: 3.50,
    description: 'Sopa de batata com alho-poró e bacon.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Caldo de Feijão',
    price: 3.50,
    description: 'Caldo de feijão preto com pedaços de carne.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Creme de Ervilha',
    price: 3.50,
    description: 'Creme de ervilha com hortelã e limão.',
    path: 'lib/images/FRANGO10.png',
  ),
  Food(
    name: 'Sopa de Cebola',
    price: 3.50,
    description: 'Sopa de cebola gratinada com queijo.',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Sopa de Lentilha',
    price: 3.50,
    description: 'Sopa de lentilha com cenoura e batata-doce.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Sopa de Abóbora',
    price: 3.50,
    description: 'Sopa de abóbora com leite de coco e curry.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Caldo de Mandioquinha',
    price: 3.50,
    description: 'Caldo de mandioquinha com carne seca.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Sopa de Abobrinha',
    price: 3.50,
    description: 'Sopa de abobrinha com hortelã e iogurte.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Sopa de Espinafre',
    price: 3.50,
    description: 'Sopa de espinafre com alho e nozes.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Caldo de Cenoura',
    price: 3.50,
    description: 'Caldo de cenoura com gengibre e mel.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Creme de Batata-doce',
    price: 3.50,
    description: 'Creme de batata-doce com coco ralado.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Sopa de Ervilha',
    price: 3.50,
    description: 'Sopa de ervilha com presunto e hortelã.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Caldo de Peixe',
    price: 3.50,
    description: 'Caldo de peixe com mariscos e coentro.',
    path: 'lib/images/FRANGO10.png',
  ),
  Food(
    name: 'Sopa de Beterraba',
    price: 3.50,
    description: 'Sopa de beterraba com iogurte natural.',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Sopa de Grão-de-bico',
    price: 3.50,
    description: 'Sopa de grão-de-bico com espinafre.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Sopa de Inhame',
    price: 3.50,
    description: 'Sopa de inhame com alho e gengibre.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Caldo de Camarão',
    price: 3.50,
    description: 'Caldo de camarão com coentro e limão.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Sopa de Cogumelos',
    price: 3.50,
    description: 'Sopa de cogumelos com vinho branco.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Sopa de Alho-poró',
    price: 3.50,
    description: 'Sopa de alho-poró com batatas e creme.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Caldo de Carne',
    price: 3.50,
    description: 'Caldo de carne com legumes e temperos.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Sopa de Lentilhas Vermelhas',
    price: 3.50,
    description: 'Sopa de lentilhas vermelhas com especiarias.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Caldo de Legumes',
    price: 3.50,
    description: 'Caldo de legumes variados com ervas.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Sopa de Abóbora com Gengibre',
    price: 3.50,
    description: 'Sopa de abóbora com um toque de gengibre.',
    path: 'lib/images/FRANGO10.png',
  ),
  Food(
    name: 'Sopa de Alho',
    price: 3.50,
    description: 'Sopa de alho assado com croutons.',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Sopa de Cenoura',
    price: 3.50,
    description: 'Sopa de cenoura com laranja e tomilho.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Caldo de Galinha',
    price: 3.50,
    description: 'Caldo de galinha com legumes frescos.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Sopa de Batata e Alho-poró',
    price: 3.50,
    description: 'Sopa cremosa de batata com alho-poró.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Sopa de Brócolis',
    price: 3.50,
    description: 'Sopa de brócolis com queijo cheddar.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Creme de Milho',
    price: 3.50,
    description: 'Creme de milho com pimenta e coentro.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Caldo de Lentilha',
    price: 3.50,
    description: 'Caldo de lentilha com pedaços de bacon.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Sopa de Beterraba e Cenoura',
    price: 3.50,
    description: 'Sopa de beterraba com cenoura e limão.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Caldo de Carne com Legumes',
    price: 3.50,
    description: 'Caldo de carne com uma variedade de legumes.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Sopa de Lentilha com Espinafre',
    price: 3.50,
    description: 'Sopa de lentilha com espinafre e temperos.',
    path: 'lib/images/FRANGO10.png',
  ),
  Food(
    name: 'Sopa de Legumes',
    price: 3.50,
    description: 'Sopa quente com uma mistura de legumes frescos.',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Caldo de Frango',
    price: 3.50,
    description: 'Caldo nutritivo com pedaços de frango e ervas.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Sopa de Milho',
    price: 3.50,
    description: 'Sopa cremosa de milho com temperos suaves.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Creme de Abóbora',
    price: 3.50,
    description: 'Creme de abóbora com um toque de gengibre.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Sopa de Tomate',
    price: 3.50,
    description: 'Sopa de tomate com manjericão e alho.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Canja de Galinha',
    price: 3.50,
    description: 'Canja de galinha com arroz e cenoura.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Caldo Verde',
    price: 3.50,
    description: 'Caldo verde com couve e pedaços de linguiça.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Sopa de Batata',
    price: 3.50,
    description: 'Sopa de batata com alho-poró e bacon.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Caldo de Feijão',
    price: 3.50,
    description: 'Caldo de feijão preto com pedaços de carne.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Creme de Ervilha',
    price: 3.50,
    description: 'Creme de ervilha com hortelã e limão.',
    path: 'lib/images/FRANGO10.png',
  ),
  Food(
    name: 'Sopa de Cebola',
    price: 3.50,
    description: 'Sopa de cebola gratinada com queijo.',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Sopa de Lentilha',
    price: 3.50,
    description: 'Sopa de lentilha com cenoura e batata-doce.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Sopa de Abóbora',
    price: 3.50,
    description: 'Sopa de abóbora com leite de coco e curry.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Caldo de Mandioquinha',
    price: 3.50,
    description: 'Caldo de mandioquinha com carne seca.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Sopa de Abobrinha',
    price: 3.50,
    description: 'Sopa de abobrinha com hortelã e iogurte.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Sopa de Espinafre',
    price: 3.50,
    description: 'Sopa de espinafre com alho e nozes.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Caldo de Cenoura',
    price: 3.50,
    description: 'Caldo de cenoura com gengibre e mel.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Creme de Batata-doce',
    price: 3.50,
    description: 'Creme de batata-doce com coco ralado.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Sopa de Ervilha',
    price: 3.50,
    description: 'Sopa de ervilha com presunto e hortelã.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Caldo de Peixe',
    price: 3.50,
    description: 'Caldo de peixe com mariscos e coentro.',
    path: 'lib/images/FRANGO10.png',
  ),
  Food(
    name: 'Sopa de Beterraba',
    price: 3.50,
    description: 'Sopa de beterraba com iogurte natural.',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Sopa de Grão-de-bico',
    price: 3.50,
    description: 'Sopa de grão-de-bico com espinafre.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Sopa de Inhame',
    price: 3.50,
    description: 'Sopa de inhame com alho e gengibre.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Caldo de Camarão',
    price: 3.50,
    description: 'Caldo de camarão com coentro e limão.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Sopa de Cogumelos',
    price: 3.50,
    description: 'Sopa de cogumelos com vinho branco.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Sopa de Alho-poró',
    price: 3.50,
    description: 'Sopa de alho-poró com batatas e creme.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Caldo de Carne',
    price: 3.50,
    description: 'Caldo de carne com legumes e temperos.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Sopa de Lentilhas Vermelhas',
    price: 3.50,
    description: 'Sopa de lentilhas vermelhas com especiarias.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Caldo de Legumes',
    price: 3.50,
    description: 'Caldo de legumes variados com ervas.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Sopa de Abóbora com Gengibre',
    price: 3.50,
    description: 'Sopa de abóbora com um toque de gengibre.',
    path: 'lib/images/FRANGO10.png',
  ),
  Food(
    name: 'Sopa de Alho',
    price: 3.50,
    description: 'Sopa de alho assado com croutons.',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Sopa de Cenoura',
    price: 3.50,
    description: 'Sopa de cenoura com laranja e tomilho.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Caldo de Galinha',
    price: 3.50,
    description: 'Caldo de galinha com legumes frescos.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Sopa de Batata e Alho-poró',
    price: 3.50,
    description: 'Sopa cremosa de batata com alho-poró.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Sopa de Brócolis',
    price: 3.50,
    description: 'Sopa de brócolis com queijo cheddar.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Creme de Milho',
    price: 3.50,
    description: 'Creme de milho com pimenta e coentro.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Caldo de Lentilha',
    price: 3.50,
    description: 'Caldo de lentilha com pedaços de bacon.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Sopa de Beterraba e Cenoura',
    price: 3.50,
    description: 'Sopa de beterraba com cenoura e limão.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Caldo de Carne com Legumes',
    price: 3.50,
    description: 'Caldo de carne com uma variedade de legumes.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Sopa de Lentilha com Espinafre',
    price: 3.50,
    description: 'Sopa de lentilha com espinafre e temperos.',
    path: 'lib/images/FRANGO10.png',
  ),
  Food(
    name: 'Sopa de Legumes',
    price: 3.50,
    description: 'Sopa quente com uma mistura de legumes frescos.',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Caldo de Frango',
    price: 3.50,
    description: 'Caldo nutritivo com pedaços de frango e ervas.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Sopa de Milho',
    price: 3.50,
    description: 'Sopa cremosa de milho com temperos suaves.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Creme de Abóbora',
    price: 3.50,
    description: 'Creme de abóbora com um toque de gengibre.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Sopa de Tomate',
    price: 3.50,
    description: 'Sopa de tomate com manjericão e alho.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Canja de Galinha',
    price: 3.50,
    description: 'Canja de galinha com arroz e cenoura.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Caldo Verde',
    price: 3.50,
    description: 'Caldo verde com couve e pedaços de linguiça.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Sopa de Batata',
    price: 3.50,
    description: 'Sopa de batata com alho-poró e bacon.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Caldo de Feijão',
    price: 3.50,
    description: 'Caldo de feijão preto com pedaços de carne.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Creme de Ervilha',
    price: 3.50,
    description: 'Creme de ervilha com hortelã e limão.',
    path: 'lib/images/FRANGO10.png',
  ),
  Food(
    name: 'Sopa de Cebola',
    price: 3.50,
    description: 'Sopa de cebola gratinada com queijo.',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Sopa de Lentilha',
    price: 3.50,
    description: 'Sopa de lentilha com cenoura e batata-doce.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Sopa de Abóbora',
    price: 3.50,
    description: 'Sopa de abóbora com leite de coco e curry.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Caldo de Mandioquinha',
    price: 3.50,
    description: 'Caldo de mandioquinha com carne seca.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Sopa de Abobrinha',
    price: 3.50,
    description: 'Sopa de abobrinha com hortelã e iogurte.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Sopa de Espinafre',
    price: 3.50,
    description: 'Sopa de espinafre com alho e nozes.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Caldo de Cenoura',
    price: 3.50,
    description: 'Caldo de cenoura com gengibre e mel.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Creme de Batata-doce',
    price: 3.50,
    description: 'Creme de batata-doce com coco ralado.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Sopa de Ervilha',
    price: 3.50,
    description: 'Sopa de ervilha com presunto e hortelã.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Caldo de Peixe',
    price: 3.50,
    description: 'Caldo de peixe com mariscos e coentro.',
    path: 'lib/images/FRANGO10.png',
  ),
  Food(
    name: 'Sopa de Beterraba',
    price: 3.50,
    description: 'Sopa de beterraba com iogurte natural.',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Sopa de Grão-de-bico',
    price: 3.50,
    description: 'Sopa de grão-de-bico com espinafre.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Sopa de Inhame',
    price: 3.50,
    description: 'Sopa de inhame com alho e gengibre.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Caldo de Camarão',
    price: 3.50,
    description: 'Caldo de camarão com coentro e limão.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Sopa de Cogumelos',
    price: 3.50,
    description: 'Sopa de cogumelos com vinho branco.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Sopa de Alho-poró',
    price: 3.50,
    description: 'Sopa de alho-poró com batatas e creme.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Caldo de Carne',
    price: 3.50,
    description: 'Caldo de carne com legumes e temperos.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Sopa de Lentilhas Vermelhas',
    price: 3.50,
    description: 'Sopa de lentilhas vermelhas com especiarias.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Caldo de Legumes',
    price: 3.50,
    description: 'Caldo de legumes variados com ervas.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Sopa de Abóbora com Gengibre',
    price: 3.50,
    description: 'Sopa de abóbora com um toque de gengibre.',
    path: 'lib/images/FRANGO10.png',
  ),
  Food(
    name: 'Sopa de Alho',
    price: 3.50,
    description: 'Sopa de alho assado com croutons.',
    path: 'lib/images/FRANGO2.png',
  ),
  Food(
    name: 'Sopa de Cenoura',
    price: 3.50,
    description: 'Sopa de cenoura com laranja e tomilho.',
    path: 'lib/images/FRANGO9.png',
  ),
  Food(
    name: 'Caldo de Galinha',
    price: 3.50,
    description: 'Caldo de galinha com legumes frescos.',
    path: 'lib/images/FRANGO3.png',
  ),
  Food(
    name: 'Sopa de Batata e Alho-poró',
    price: 3.50,
    description: 'Sopa cremosa de batata com alho-poró.',
    path: 'lib/images/FRANGO7.png',
  ),
  Food(
    name: 'Sopa de Brócolis',
    price: 3.50,
    description: 'Sopa de brócolis com queijo cheddar.',
    path: 'lib/images/FRANGO4.png',
  ),
  Food(
    name: 'Creme de Milho',
    price: 3.50,
    description: 'Creme de milho com pimenta e coentro.',
    path: 'lib/images/FRANGO1.png',
  ),
  Food(
    name: 'Caldo de Lentilha',
    price: 3.50,
    description: 'Caldo de lentilha com pedaços de bacon.',
    path: 'lib/images/FRANGO5.png',
  ),
  Food(
    name: 'Sopa de Beterraba e Cenoura',
    price: 3.50,
    description: 'Sopa de beterraba com cenoura e limão.',
    path: 'lib/images/FRANGO8.png',
  ),
  Food(
    name: 'Caldo de Carne com Legumes',
    price: 3.50,
    description: 'Caldo de carne com uma variedade de legumes.',
    path: 'lib/images/FRANGO6.png',
  ),
  Food(
    name: 'Sopa de Lentilha com Espinafre',
    price: 3.50,
    description: 'Sopa de lentilha com espinafre e temperos.',
    path: 'lib/images/FRANGO10.png',
  ),
];
